# permissions for end users to view mydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydeployment-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - mydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - mydeployments/status
  verbs:
  - get
