# permissions for end users to edit myexternaldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myexternaldeployment-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - myexternaldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - myexternaldeployments/status
  verbs:
  - get
