# permissions for end users to view myexternaldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myexternaldeployment-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - myexternaldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - myexternaldeployments/status
  verbs:
  - get
