---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for cache.example.com/v1, Kind: Memcached
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - memcacheds
      - memcacheds/status
      - memcacheds/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for cache.example.com/v1alpha1, Kind: MyDeployment
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - mydeployments
      - mydeployments/status
      - mydeployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for cache.example.com/v1, Kind: MyExternalDeployment
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - myexternaldeployments
      - myexternaldeployments/status
      - myexternaldeployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
